CREATE TABLE links (
  id SERIAL PRIMARY KEY,
  code VARCHAR(8) NOT NULL UNIQUE,
  target TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  total_clicks INTEGER DEFAULT 0,
  last_clicked TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

CREATE INDEX idx_links_code ON links(code);
